- name: "Actualizamos el sistema"
  apt: update_cache=yes upgrade=yes

#- name: "Install adrian ssh key"
#  authorized_key: 
#    user: vagrant
#    state: present
#    key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
