- name: "Configurar /etc/network/interfaces"
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: reboot
  reboot:
  timeout: 1
  ignore_errors: yes