- name: "Activar bit de forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes

- name: "Configurar /etc/network/interfaces"
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  #notify: 
    #- reboot
    